export const ORDER_ACTION_TYPES = {
  ORDER_CREATE_REQUEST: "ORDER_CREATE_REQUEST",
  ORDER_CREATE_SUCCESS: "ORDER_CREATE_SUCCESS",
  ORDER_CREATE_FAIL: "ORDER_CREATE_FAIL",
  ORDER_CREATE_RESET: "ORDER_CREATE_RESET",

  ORDER_DETAILS_REQUEST: "ORDER_DETAILS_REQUEST",
  ORDER_DETAILS_SUCCESS: "ORDER_DETAILS_SUCCESS",
  ORDER_DETAILS_FAIL: "ORDER_DETAILS_FAIL",

  ORDER_PAY_REQUEST: "ORDER_PAY_REQUEST",
  ORDER_PAY_SUCCESS: "ORDER_PAY_SUCCESS",
  ORDER_PAY_FAIL: "ORDER_PAY_FAIL",
  ORDER_PAY_RESSET: "ORDER_PAY_RESSET",

  USER_ORDERS_REQUEST: "USER_ORDERS_REQUEST",
  USER_ORDERS_SUCCESS: "USER_ORDERS_SUCCESS",
  USER_ORDERS_FAIL: "USER_ORDERS_FAIL",
};
