export const CART_ITEMS_TYPES = {
  ADD_CART_ITEMS: "ADD_CART_ITEMS",
  REMOVE_CART_ITEMS: "REMOVE_CART_ITEMS",
};

export const SHIPPING_ADRESS = {
  SAVE_SHIPPING_ADRESS: "SAVE_SHIPPING_ADRESS",
};

export const PAYMEENT_METHODES = {
  SAVE_PAYMEENT_METHODES: "SAVE_PAYMEENT_METHODES",
};
