export const PRODUCTS_ACTION_TYPES = {
  PRODUCTS_LIST_REQUEST: "PRODUCTS_LIST_REQUEST",
  PRODUCTS_LIST_SUCCESS: "PRODUCTS_LIST_SUCCESS",
  PRODUCTS_LIST_FAIL: "PRODUCTS_LIST_FAIL",
};

export const PRODUCT_ACTION_TYPES = {
  PRODUCT_DETAILS_REQUEST: "PRODUCT_DETAILS_REQUEST",
  PRODUCT_DETAILS_SUCCESS: "PRODUCT_DETAILS_SUCCESS",
  PRODUCT_DETAILS_FAIL: "PRODUCT_DETAILS_FAIL",
};
